# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0002_auto_20170321_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='course',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
